services:
  # Base de Datos
  db:
    image: postgres:15-alpine
    container_name: tutor_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=tutor_django
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Compilador Seguro
  compiler:
    image: ghcr.io/engineer-man/piston
    container_name: tutor_compiler
    privileged: true
    ports:
      - "2000:2000"
    tmpfs:
      - /piston/jobs
      - /tmp

volumes:
  postgres_data:
