# Generated by Django 6.0.3 on 2026-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_make_user_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Nueva conversación', max_length=200),
        ),
    ]
