# Generated by Django 6.0.3 on 2026-03-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_title_to_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
