# Generated by Django 6.0.3 on 2026-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_moderated_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
