# Generated by Django 6.0.3 on 2026-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsession_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_mode', models.CharField(choices=[('both', 'Input + Output'), ('input', 'Solo Input'), ('output', 'Solo Output'), ('none', 'Desactivada')], default='both', help_text='Qué moderación aplicar a los mensajes del chat.', max_length=10, verbose_name='Modo de moderación')),
                ('llm_model', models.CharField(default='llama3.2', help_text='Nombre del modelo de Ollama para el tutor (ej: llama3.2, phi4-mini-reasoning).', max_length=100, verbose_name='Modelo LLM principal')),
                ('moderation_model', models.CharField(default='llama3.2', help_text='Nombre del modelo de Ollama para la moderación de contenido.', max_length=100, verbose_name='Modelo LLM de moderación')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
