# Generated by Django 6.0.3 on 2026-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_systemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='llm_model',
            field=models.CharField(default='google/gemma-4-31b-it:free', help_text='Nombre del modelo en OpenRouter para el tutor (ej: google/gemma-4-31b-it:free).', max_length=100, verbose_name='Modelo LLM principal'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='moderation_model',
            field=models.CharField(default='google/gemma-4-31b-it:free', help_text='Nombre del modelo en OpenRouter para la moderación de contenido.', max_length=100, verbose_name='Modelo LLM de moderación'),
        ),
    ]
