# Generated by Django 6.0.3 on 2026-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='mod_word_window',
            field=models.PositiveIntegerField(default=40, help_text='Cada cuántas palabras del output se lanza un check de moderación.', verbose_name='Ventana de moderación (palabras)'),
        ),
    ]
