# Generated by Django 6.0.3 on 2026-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_systemconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='llm_model',
            field=models.CharField(default='gemini-2.0-flash', help_text='Nombre del modelo de Gemini para el tutor (ej: gemini-2.0-flash, gemini-2.5-flash-preview-04-17).', max_length=100, verbose_name='Modelo LLM principal'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='moderation_model',
            field=models.CharField(default='gemini-2.0-flash', help_text='Nombre del modelo de Gemini para la moderación de contenido.', max_length=100, verbose_name='Modelo LLM de moderación'),
        ),
    ]
